version: '3.8'

services:
  db:
    image: postgres:14-alpine
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - notify/.env
    ports:
      - '5432'
    networks:
      - skill_notify_network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER' ]
      interval: 50s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    env_file:
      - notify/.env
    networks:
      - skill_notify_network
    depends_on:
      - db
    ports:
      - '${PORT}:8000'
    volumes:
      - /var/logs/container:/app/app/logs

networks:
  skill_notify_network:

volumes:
  postgres_data:
